import Link from "next/link";
import { QrCode, ArrowLeft } from "lucide-react";

export const metadata = { title: "Terms & Conditions – QR Order" };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-background/80 backdrop-blur sticky top-0 z-10">
        <div className="mx-auto max-w-3xl px-6 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-orange-500 to-amber-500">
              <QrCode className="h-4 w-4 text-white" />
            </div>
            <span className="font-bold text-sm">QR Order</span>
          </Link>
          <Link href="/" className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="h-3.5 w-3.5" /> Back
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <div className="mb-8">
          <p className="text-xs text-muted-foreground uppercase tracking-wider mb-2">Legal</p>
          <h1 className="text-3xl font-bold">Terms &amp; Conditions</h1>
          <p className="text-sm text-muted-foreground mt-2">Last updated: April 2025</p>
        </div>

        <div className="prose prose-sm dark:prose-invert max-w-none space-y-6 text-sm leading-relaxed text-muted-foreground">

          <p>
            This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <p>
            This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, requiring publication of rules, regulations, privacy policy, and Terms of Use for access or usage of <strong className="text-foreground">https://assistt.in/</strong> ("Platform"), including the related web application.
          </p>

          <p>
            The Platform is owned and operated by <strong className="text-foreground">QR Order</strong>, a product of Assistt, with its registered office at Deshbandhu Para, Siliguri, West Bengal ("Platform Owner", "we", "us", "our").
          </p>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Platform — including creating a restaurant account, managing menus, processing orders, or using any feature of the QR ordering system — you agree to be bound by these Terms of Use. If you do not agree, please do not use the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">2. Use of the Platform</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You agree to provide accurate and complete information when registering your restaurant account.</li>
              <li>You are responsible for all activity that occurs under your account, including actions by your staff (waiters, kitchen staff, managers).</li>
              <li>You agree not to use the Platform for any unlawful purpose or in violation of applicable Indian laws.</li>
              <li>You must not attempt to reverse-engineer, copy, or redistribute any part of the Platform.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">3. Subscription &amp; Billing</h2>
            <p>
              Access to certain features requires a paid subscription (Pro Plan). By subscribing, you authorise us to charge the applicable fees via Stripe. Subscription fees are non-refundable except as described in our Refund Policy. We reserve the right to modify pricing with reasonable notice.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">4. Intellectual Property</h2>
            <p>
              The Platform, its design, code, and content are proprietary to QR Order and protected by applicable intellectual property laws. You retain ownership of your restaurant data (menus, orders, customer information) but grant us a licence to process it to provide the Services.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">5. Disclaimer of Warranties</h2>
            <p>
              The Platform is provided "as is". We do not warrant uninterrupted, error-free operation. We are not liable for any loss of orders, revenue, or data arising from downtime, bugs, or third-party service failures (including payment processors or internet connectivity).
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">6. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, QR Order's total liability to you shall not exceed the subscription fees paid by you in the three months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">7. Termination</h2>
            <p>
              We may suspend or terminate your account if you violate these Terms, fail to pay subscription fees, or engage in fraudulent activity. You may cancel your subscription at any time from your billing settings.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">8. Governing Law</h2>
            <p>
              These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in Siliguri, West Bengal.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">9. Changes to Terms</h2>
            <p>
              We may update these Terms at any time. Continued use of the Platform after changes constitutes acceptance. We will notify registered users of material changes via email.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">10. Business Details</h2>
            <div className="p-4 rounded-xl border bg-card space-y-1 text-sm">
              <p><strong className="text-foreground">Ramanuj Dey Sarkar</strong></p>
              <p>Proprietor, Assistt</p>
              <p>Deshbandhu Para, Siliguri, West Bengal, India</p>
              <p>Phone: <a href="tel:+918250622813" className="text-primary hover:underline">+91 82506 22813</a></p>
              <p>Email: <a href="mailto:support@assistt.in" className="text-primary hover:underline">support@assistt.in</a></p>
            </div>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-2">11. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="mailto:support@assistt.in" className="text-primary hover:underline">support@assistt.in</a>.</p>
          </section>
        </div>
      </main>

      <footer className="border-t py-6 text-center text-xs text-muted-foreground">
        <div className="flex items-center justify-center gap-4">
          <Link href="/terms" className="hover:text-foreground">Terms</Link>
          <Link href="/privacy" className="hover:text-foreground">Privacy</Link>
          <Link href="/refunds" className="hover:text-foreground">Refunds</Link>
          <Link href="/shipping" className="hover:text-foreground">Shipping</Link>
        </div>
        <p className="mt-2">© {new Date().getFullYear()} <strong className="text-foreground">Assistt</strong> · QR Order · All rights reserved</p>

      </footer>
    </div>
  );
}
